create table USER
(
	ID BIGINT auto_increment,
	ACCOUNT_ID VARCHAR(100),
	NAME VARCHAR(50),
	TOKEN VARCHAR(36),
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	BIO VARCHAR(256),
	AVATAR_URL VARCHAR(100),
	constraint USER_PK
		primary key (ID)
);
create table QUESTION
(
	ID BIGINT auto_increment,
	TITLE VARCHAR(50),
	DESCRIPTION TEXT,
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	CREATOR BIGINT,
	COMMENT_COUNT INT default 0,
	VIEW_COUNT INT default 0,
	LIKE_COUNT INT default 0,
	TAG VARCHAR(256),
	constraint QUESTION_PK
		primary key (ID)
);
create table COMMENT
(
	ID BIGINT auto_increment,
	PARENT_ID BIGINT not null,
	TYPE INT not null,
	COMMENTATOR BIGINT not null,
	GMT_CREATE BIGINT,
	GMT_MODIFIED BIGINT,
	LIKE_COUNT BIGINT default 0,
	CONTENT VARCHAR(1024),
	COMMENT_COUNT INT default 0,
	constraint COMMENT_PK
		primary key (ID)
);
create table NOTIFICATION
(
	ID BIGINT auto_increment,
	NOTIFIER BIGINT not null,
	RECEIVER BIGINT not null,
	OUTERID BIGINT not null,
	TYPE INT not null,
	GMT_CREATE BIGINT not null,
	STATUS INT default 0 not null,
	NOTIFIER_NAME VARCHAR(100),
	OUTER_TITLE VARCHAR(256),
	constraint NOTIFICATION_PK
		primary key (ID)
);






